[project]
authors = [
  { name = "A.suzuki", email = "suzu.devworks@gmail.com" },
]
dependencies = [
  "natsort>=8.4.0",
  "numpy>=2.1.2",
  "pytz>=2024.2",
]
description = "Add your description here"
name = "examples-lib"
readme = "README.md"
requires-python = ">= 3.12"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[dependency-groups]
dev = [
  "pytest-asyncio>=0.24.0",
  "pytest-cov>=5.0.0",
  "types-pytz>=2024.2.0.20240913",
]

[tool.pytest.ini_options]
addopts = "-p no:cacheprovider"
asyncio_default_fixture_loop_scope = "function"
asyncio_mode = "auto"
markers = [
  "asyncio",
]
