[project]
authors = [
  { name = "A.suzuki", email = "suzu.devworks@gmail.com" },
]
dependencies = [
  "posix-ipc>=1.1.1",
  "sysv-ipc>=1.1.0",
]
description = "Add your description here"
name = "examples-ipc"
readme = "README.md"
requires-python = ">= 3.12"
version = "0.1.0"

[project.scripts]
"examples-ipc" = "examples_ipc:main"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = "posix_ipc.*"
