[project]
authors = [
  { name = "A.suzuki", email = "suzu.devworks@gmail.com" },
]
description = "Add your description here"
name = "examples-py"
readme = "README.md"
requires-python = ">= 3.12,< 3.14"
version = "0.1.0"

[tool.uv.workspace]
exclude = ["packages/*/*scripts"]
members = ["packages/*/*"]

[dependency-groups]
dev = [
  "mypy>=2.3.0",
  "pyclean>=3.7.0",
  "pytest-asyncio>=1.4.0",
  "pytest-cov>=7.1.0",
  "pytest>=9.1.1",
  "ruff>=0.16.0",
]
