[project]
authors = [
  {name = "A.suzuki", email = "suzu.devworks@gmail.com"},
]
dependencies = []
description = "Default template for PDM package"
license = {text = "MIT"}
name = "examples-packaging-pdm"
readme = "README.md"
requires-python = ">=3.12"
version = "0.1.0"

[project.scripts]
examples-pdm-cli = "examples_packaging_pdm.console.command:main"

[build-system]
build-backend = "pdm.backend"
requires = ["pdm-backend"]

[tool.pdm]
distribution = true
version = {source = "file", path = "src/examples_packaging_pdm/__version__.py"}
# version = {source = "scm", write_to = "examples_packaging_pdm/models/VERSION"}

[tool.pytest.ini_options]
addopts = "-p no:cacheprovider"

[tool.black]
line-length = 119

[tool.isort]
line_length = 119
profile = "black"

[tool.pdm.scripts]
clean = "pyclean ."
lint = "flake8"
test = "pytest"
