version: 1
disable_existing_loggers: false
formatters:
  default:
    format: "%(asctime)s [%(levelname)-5s]%(name)s[%(lineno)s]: %(message)s"
  parallel:
    format:
      "%(asctime)s [%(levelname)-5s](%(process)d,%(thread)d)%(name)s[%(lineno)s]:
      %(message)s"
  simple:
    format: "%(asctime)s [%(levelname)-5s] %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
  rotating_file_by_size:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: parallel
    filename: "logs/console-sizing.log"
    maxBytes: 1048576
    backupCount: 3
    encoding: utf-8
  rotating_file_by_week:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: default
    filename: "logs/console-week.log"
    when: W5
    interval: 1
    backupCount: 5
    encoding: utf-8
loggers:
  examples:
    level: DEBUG
    handlers:
      - console
      - rotating_file_by_size
      - rotating_file_by_week
    propagate: false
root:
  level: INFO
  handlers:
    - console
    - rotating_file_by_size
    - rotating_file_by_week
