[tool.poetry]
authors = ["A.suzuki <suzu.devworks@gmail.com>"]
description = ""
name = "examples-packaging-poetry"
packages = [{include = "examples_packaging_poetry", from = "src"}]
readme = "README.md"
version = "0.1.0"

[tool.poetry.scripts]
examples-poetry-cli = 'examples_packaging_poetry.console.command:main'

[tool.poetry.dependencies]
python = "^3.12"

[tool.poetry.group.dev.dependencies]
black = "^24.3.0"
flake8 = "^6.0.0"
isort = "^5.12.0"
mypy = "^1.3.0"
pyclean = "^2.7.2"
pytest-cov = "^4.0.0"
taskipy = "^1.10.4"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.black]
line-length = 119

[tool.isort]
include_trailing_comma = true
known_local_folder = ['config']
line_length = 119
multi_line_output = 3

[tool.flake8]
ignore = "E203,E266,W503,"
max-complexity = 18
max-line-length = 119

[tool.mypy]
check_untyped_defs = true
ignore_missing_imports = true
no_strict_optional = true
python_version = "3.11"

[tool.taskipy.tasks]
black = "black src/ tests/"
clean = "pyclean ."
lint = "flake8 "
test = "pytest"
