name: CI

on:
  push:
    branches:
      - develop
    paths:
      - ".github/workflows/ci.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "packages/**"
  workflow_dispatch:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v7

    - name: Install uv
      uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python
      uses: actions/setup-python@v7
      with:
        python-version-file: "pyproject.toml"

    - name: Install dependencies
      run: uv sync --all-packages --all-extras

    - name: Lint with ruff
      uses: astral-sh/ruff-action@v4.1.0
      with:
        src: "./packages"

    - name: Lint with Mypy
      run: uv run mypy --config-file=./.mypy.ini "./packages"

    - name: Test with pytest
      run: uv run pytest --junitxml=test-results/pytest-report.xml "./packages"
      continue-on-error: true

    - uses: actions/upload-artifact@v7
      if: ${{ !cancelled() }}
      with:
        name: pytest-results
        path: test-results/

