name: CI

on:
  push:
    branches:
      - "main"
    paths:
      - "packages/**"
  pull_request:
    paths:
      - "packages/**"
      - ".github/workflows/py-ci.yaml"
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v7

    - name: Install uv
      uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Set up Python
      uses: actions/setup-python@v7
      with:
        python-version-file: "pyproject.toml"

    - name: Install dependencies
      run: uv sync --all-packages --all-extras

    - name: Lint with ruff
      uses: astral-sh/ruff-action@v4.1.0
      with:
        src: ./packages

    - name: Lint with Mypy
      run: uv run mypy --config-file=./.mypy.ini ./packages

    - name: Test with pytest
      run: |
        uv run pytest \
          --junitxml=./test-results/pytest-report.xml \
          --ignore=./packages/web/examples-playwright/ \
          ./packages

    - uses: actions/upload-artifact@v7
      if: ${{ !cancelled() }}
      with:
        name: pytest-results
        path: ./test-results/

